[project]
name = "dataset-recsys"
version = "0.1.0"
description = "Dataset recommender for the DataGEMS project"
authors = [
    { name = "Stavroula Eleftherakis", email = "selefth@yahoo.com" },
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.11,<4.0"
dynamic = ["dependencies"]

[tool.poetry]
packages = [{ include = "dataset_recsys" }, { include = "recs_metrics" }]

[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.121.0"
dotenv = "^0.9.9"
uvicorn = "^0.38.0"
boto3 = "^1.40.66"
pandas = "^2.3.3"
redis = "^7.1.0"
structlog = "^25.5.0"
httpx = "^0.28.1"
python-jose = "^3.5.0"
pydantic-settings = "^2.13.1"
iniconfig = "^2.3.0"
psycopg2-binary = "^2.9.11"
chonky = "0.1.7"
torch = [
    { version = ">=2.6.0", source = "pytorch-cpu", markers = "platform_system != 'Darwin'" },
    { version = ">=2.6.0", markers = "platform_system == 'Darwin'" },
]
sentence-transformers = "3.0.1"
yt-dlp = "^2026.3.17"
faster-whisper = "^1.2.1"
openpyxl = "^3.1.5"

[tool.poetry.group.ir]
optional = true

[tool.poetry.group.ir.dependencies]
pyserini = "^1.3.0"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.6.1"
mkdocs-material = "^9.7.0"
mike = "^2.1.3"
neoteroi-mkdocs = "^1.1.3"
pymdown-extensions = "^10.17.1"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^8.4.2"

[tool.poetry.group.notebook]
optional = true

[tool.poetry.group.notebook.dependencies]
jupyter = "^1.1.1"
ipywidgets = "^8.1.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
